# -*- coding: utf-8 -*-
"""2.5 Classification quality metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBa0KW786ro0l1HMsoKZTL10Cd0EwR2B
"""

from google.colab import files
files.upload()

import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score, roc_curve, roc_auc_score
import matplotlib.pyplot as plt

df = pd.read_csv('data_metrics.csv')
thresh = 0.5
df['predicted_RF'] = (df.model_RF >= 0.5).astype('int')
df['predicted_LR'] = (df.model_LR >= 0.5).astype('int')
df.head()

def find_TP(y_true, y_pred):
    # counts the number of true positives (y_true = 1, y_pred = 1)
    return sum((y_true == 1) & (y_pred == 1))
def find_FN(y_true, y_pred):
    # counts the number of false negatives (y_true = 1, y_pred = 0)
    return sum((y_true == 1) & (y_pred == 0))
def find_FP(y_true, y_pred):
    # counts the number of false positives (y_true = 0, y_pred = 1)
    return sum((y_true == 0) & (y_pred == 1))
def find_TN(y_true, y_pred):
    # counts the number of true negatives (y_true = 0, y_pred = 0)
    return sum((y_true == 0) & (y_pred == 0))

print('TP =', find_TP(df.actual_label.values, df.predicted_RF.values))
print('FN =', find_FN(df.actual_label.values, df.predicted_RF.values))
print('FP =', find_FP(df.actual_label.values, df.predicted_RF.values))
print('TN =', find_TN(df.actual_label.values, df.predicted_RF.values))
print('')

def find_conf_matrix_values(y_true, y_pred):
    # calculate TP, FN, FP, TN
    TP = find_TP(y_true, y_pred)
    FN = find_FN(y_true, y_pred)
    FP = find_FP(y_true, y_pred)
    TN = find_TN(y_true, y_pred)
    return TP, FN, FP, TN
def kharin_confusion_matrix(y_true, y_pred):
    TP, FN, FP, TN = find_conf_matrix_values(y_true, y_pred)
    return np.array([[TN, FP], [FN, TP]])

kharin_confusion_matrix(df.actual_label.values, df.predicted_RF.values)

assert np.array_equal(kharin_confusion_matrix(df.actual_label.values, df.predicted_RF.values), confusion_matrix(df.actual_label.values, df.predicted_RF.values) ), 'kharin_confusion_matrix() is not correct for RF'
assert np.array_equal(kharin_confusion_matrix(df.actual_label.values, df.predicted_LR.values), confusion_matrix(df.actual_label.values, df.predicted_LR.values) ), 'kharin_confusion_matrix() is not correct for LR'

def kharin_accuracy_score(y_true, y_pred):
    # calculates the fraction of samples
    TP, FN, FP, TN = find_conf_matrix_values(y_true, y_pred)
    return (TP + TN) / (TP + TN + FP + FN)
assert kharin_accuracy_score(df.actual_label.values, df.predicted_LR.values) == accuracy_score(df.actual_label.values, df.predicted_LR.values), 'kharin_accuracy_score failed on LR'
print('Accuracy RF: %.3f'%(kharin_accuracy_score(df.actual_label.values, df.predicted_RF.values)))
print('Accuracy LR: %.3f'%(kharin_accuracy_score(df.actual_label.values, df.predicted_LR.values)))

def kharin_recall_score(y_true, y_pred):
    # calculates the fraction of positive samples predicted correctly
    TP, FN, FP, TN = find_conf_matrix_values(y_true, y_pred)
    return TP / (TP + FN)
assert kharin_recall_score(df.actual_label.values, df.predicted_LR.values) == recall_score(df.actual_label.values, df.predicted_LR.values), 'kharin_accuracy_score failed on LR'
print('Recall RF: %.3f'%(kharin_recall_score(df.actual_label.values, df.predicted_RF.values)))
print('Recall LR: %.3f'%(kharin_recall_score(df.actual_label.values, df.predicted_LR.values)))

def kharin_precision_score(y_true, y_pred):
    # calculates the fraction of predicted positives samples that are actually positive
    TP, FN, FP, TN = find_conf_matrix_values(y_true, y_pred)
    return TP / (TP + FP)
assert kharin_precision_score(df.actual_label.values, df.predicted_LR.values) == precision_score(df.actual_label.values, df.predicted_LR.values), 'kharin_accuracy_score failed on LR'
print('Precision RF: %.3f'%(kharin_precision_score(df.actual_label.values, df.predicted_RF.values)))
print('Precision LR: %.3f'%(kharin_precision_score(df.actual_label.values, df.predicted_LR.values)))

def kharin_f1_score(y_true, y_pred):
    # calculates the F1 score
    recall = kharin_recall_score(y_true, y_pred)
    precision = kharin_precision_score(y_true, y_pred)
    return 2 * (precision * recall) / (precision + recall)
assert np.isclose(kharin_f1_score(df.actual_label.values, df.predicted_LR.values), f1_score(df.actual_label.values, df.predicted_LR.values)), 'kharin_f1_score failed on LR'
print('F1 RF: %.3f'%(kharin_f1_score(df.actual_label.values, df.predicted_RF.values)))
print('F1 LR: %.3f'%(kharin_f1_score(df.actual_label.values, df.predicted_LR.values)))

print('')

print('scores with threshold = 0.5')
print('Accuracy RF: %.3f'%(kharin_accuracy_score(df.actual_label.values, df.predicted_RF.values)))
print('Recall RF: %.3f'%(kharin_recall_score(df.actual_label.values, df.predicted_RF.values)))
print('Precision RF: %.3f'%(kharin_precision_score(df.actual_label.values, df.predicted_RF.values)))
print('F1 RF: %.3f'%(kharin_f1_score(df.actual_label.values, df.predicted_RF.values)))
print('')
print('scores with threshold = 0.25')
print('Accuracy RF: %.3f'%(kharin_accuracy_score(df.actual_label.values, (df.model_RF >= 0.25).astype('int').values)))
print('Recall RF: %.3f'%(kharin_recall_score(df.actual_label.values, (df.model_RF >= 0.25).astype('int').values)))
print('Precision RF: %.3f'%(kharin_precision_score(df.actual_label.values, (df.model_RF >= 0.25).astype('int').values)))
print('F1 RF: %.3f'%(kharin_f1_score(df.actual_label.values, (df.model_RF >= 0.25).astype('int').values)))

thresholds_RF = roc_curve(df.actual_label.values, df.model_RF.values)
fpr_LR, tpr_LR, thresholds_LR = roc_curve(df.actual_label.values, df.model_LR.values)

auc_RF = roc_auc_score(df.actual_label.values, df.model_RF.values)
auc_LR = roc_auc_score(df.actual_label.values, df.model_LR.values)

print('')

print('AUC RF: %.3f' % auc_RF)
print('AUC LR: %.3f' % auc_LR)

fpr_RF, tpr_RF, thresholds_RF = roc_curve(df.actual_label.values, df.model_RF.values)
fpr_LR, tpr_LR, thresholds_LR = roc_curve(df.actual_label.values, df.model_LR.values)

plt.plot(fpr_RF, tpr_RF, 'r-', label='RF AUC: %.3f' % auc_RF)
plt.plot(fpr_LR, tpr_LR, 'b-', label='LR AUC: %.3f' % auc_LR)
plt.plot([0, 1], [0, 1], 'k-', label='random')
plt.plot([0, 0, 1, 1], [0, 1, 1, 1], 'g-', label='perfect')
plt.legend()
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.show()