# -*- coding: utf-8 -*-
"""2.6 Support Vector Machine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lZmIJJQM-aEM8_SFpjk8yE83afdwQlpk
"""

from google.colab import files
files.upload()

import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

# Завантаження даних із вхідного файлу
data = np.loadtxt('data_multivar_nb.txt', delimiter = ',')
X, y = data[:, :-1], data[:, -1]

# Розбивка даних на навчальний та тестовий набори
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 3)

# Створення класифікатора
classifier = svm.SVC(kernel = 'linear', C = 1)

# Тренування класифікатора
classifier.fit(X_train, y_train)

# Прогнозування значень для тренувальних даних
y_pred = classifier.predict(X_test)

# Обчислення якості класифікатора
print('SVM accuracy:', accuracy_score(y_test, y_pred))
print('SVM recall:', recall_score(y_test, y_pred, average='weighted'))
print('SVM precision:', precision_score(y_test, y_pred, average='weighted'))
print('SVM f1 score:', f1_score(y_test, y_pred, average='weighted'))